# Generated by Django 5.1.4 on 2025-01-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_account_account_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
