# Generated by Django 5.1.4 on 2025-01-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_inventory_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_item_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
